import os
import shutil

prefixes = [
    "IBlSB",
    "SiHrU",
    "coXSB",
    "mvyQh",
    "vcCwj",
    "bDylN",
    "RyNbU",
    "YFyAk",
    "Yajjl",
    "ugzEf",
    "pUDvZ",
    "cEkwI",
    "YypTw",
    "Pwozb",
    "UPAKV",
    "kcMoG",
    "AVAqS",
    "rXzde",
    "kkZJK",
    "aaXOC",
    "QIoBp",
    "hUSnL",
    "dBYTx",
    "pRvIl",
    "gJQbg",
    "IWbtj",
    "OIxJj",
    "iguGp",
    "KKocB",
    "lYqMu",
    "EYLuP",
    "mLkIC",
    "lnFzk",
    "VIfCG",
    "QpSnJ",
    "CHaOH",
    "MiaeK",
    "QQkpS",
    "Jofdw",
    "UVogL",
    "yeWeS",
    "xLXxZ",
    "fifkI",
    "ZVoos",
    "vgePQ",
    "cURGf",
    "rBEUC",
    "Rfuka",
    "oaGRm",
    "xEwSP",
    "ycvmG",
    "SDAcR",
    "uVOQW",
    "smFus",
    "gzMqJ",
    "NMAPy",
    "dmMjE",
    "AXnMd",
    "GVutl",
    "OOHEf",
    "wcgVM",
    "kRnHu",
    "hDdbL",
    "hUHbh",
    "Vtpqh",
    "QxIhc",
    "rXxtX",
    "WRGFg",
    "lzLGu",
    "zPFQM",
    "hwmzm",
    "GXQiH",
    "qnqEW",
    "Ivflt",
    "ZAlrL",
    "efbtm",
    "zReQb",
    "eOnJm",
    "SdZlB",
    "bYvsS",
    "qRSAz",
    "ZWsym",
    "IKBkQ",
    "cHqfV",
    "zUOYV",
    "SfktE",
    "uWvLg",
    "hTDPS",
    "eKVcd",
    "Cdmbm",
    "oUNrA",
    "getRs",
    "YhqAP",
    "UUYal",
    "kGJWA",
    "eSSdn",
    "Zwqpk",
    "HYoXu",
    "FkjIZ",
    "Bsnpr",
    "IQoMl",
    "uqXhf",
    "guBDw",
    "vPolA",
    "KkYfa",
    "OvZjX",
    "BoJax",
    "KjdzE",
    "wnaJN",
    "dDYpA",
    "GaBNr",
    "DDVlO",
    "JPiuq",
    "PVNMH",
    "DYziy",
    "aYkRt",
    "HXcfL",
    "CakBl",
    "vnyHX",
    "HMySY",
    "yZdiA",
    "vtxRJ",
    "irwzI",
    "JFBlh",
    "RPKgO",
    "oTtgU",
    "lOJMe",
    "VlOBH",
    "xgrHv",
    "abuaI",
    "Spmbk",
    "fwduy",
    "DJRWm",
    "rBxgH",
    "DtnrP",
    "QxcoR",
    "baTBM",
    "ARWTp",
    "GGXsH",
    "BziiA",
    "HEwxn",
    "jDjCy",
    "aYDKE",
    "rblZm",
    "FNkdX",
    "pOFGL",
    "RsgPf",
    "DAKQF",
    "TueYu",
    "EBSeG",
    "RBROA",
    "koPqa",
    "bHYgT",
    "jwkpZ",
    "vvzzv",
    "jxvAE",
]

root = "assets/labyrinth"

paths = ["/".join(prefixes[start:start+12]) for start in range(0, 156, 12)]

for path in paths:
    pathname = f"{root}/{path}/"
    os.makedirs(pathname, exist_ok=True)
    print(f"Created {pathname}")

for root, dirs, files in os.walk(root):
    for idx, dir in enumerate(dirs):
        with open(os.path.join(root, dir, "README.md"), "w") as f:
            f.writelines([
                f"# {dir}\n",
                f"_walking the labyrinth..._"
            ])

        if idx % 3 == 0:
            dir_prefix = dir.split("/")[-1]
            print(dir_prefix)
            shutil.copy("assets/labyrinth/AAAAA.pdf", os.path.join(root, dir, f"{dir_prefix}.pdf"))

        
